id: I3FDCAAB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:25:32+00:00'
last_modified: '2022-06-08T10:53:08.071400+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC465
  title: 'གྲངས་རིག་རིག་གནས་དང་བོད་རྒྱའི་སྐད་གཉིས་གྲངས་རིག་སློབ་གསོའི་སྤྱི་དོན་བློ་གྲོས་སྣང་བ་འདྲེན་པའི་སྐྱ་རེངས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    0519:
      image_group_id: I2PD18729
      title: Volume 1 of grangs rig rig gnas dang bod rgya'i skad gnyis grangs rig
        slob gso'i spyi don blo gros snang ba 'dren pa'i skya rengs/
      total_pages: 342
      order: 1
      base_file: 0519.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
