id: opecha:P006993
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC465
  title: 'གྲངས་རིག་རིག་གནས་དང་བོད་རྒྱའི་སྐད་གཉིས་གྲངས་རིག་སློབ་གསོའི་སྤྱི་དོན་བློ་གྲོས་སྣང་བ་འདྲེན་པའི་སྐྱ་རེངས། '
  volume:
    0ce63c9b969943dd977a9ebc7d66958a:
      image_group_id: I2PD18729
      title: Volume 1 of grangs rig rig gnas dang bod rgya'i skad gnyis grangs rig
        slob gso'i spyi don blo gros snang ba 'dren pa'i skya rengs/
      volume_number: 1
      total_pages: 342
  author: ''
ebook_metadata:
  title: 'གྲངས་རིག་རིག་གནས་དང་བོད་རྒྱའི་སྐད་གཉིས་གྲངས་རིག་སློབ་གསོའི་སྤྱི་དོན་བློ་གྲོས་སྣང་བ་འདྲེན་པའི་སྐྱ་རེངས། '
  author: ''
  sku: P006993
  cover: cover.jpg
  layers:
  - pagination
