id: P006993
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC465
  title: 'གྲངས་རིག་རིག་གནས་དང་བོད་རྒྱའི་སྐད་གཉིས་གྲངས་རིག་སློབ་གསོའི་སྤྱི་དོན་བློ་གྲོས་སྣང་བ་འདྲེན་པའི་སྐྱ་རེངས། '
  author: ''
  volumes:
    1cc6ba82fbd844efac443c24101c8371:
      image_group_id: I2PD18729
      title: ''
      volume_number: 1
      total_pages: 342
ebook_metadata:
  title: 'གྲངས་རིག་རིག་གནས་དང་བོད་རྒྱའི་སྐད་གཉིས་གྲངས་རིག་སློབ་གསོའི་སྤྱི་དོན་བློ་གྲོས་སྣང་བ་འདྲེན་པའི་སྐྱ་རེངས། '
  author: ''
  sku: P006993
  cover: cover.jpg
  layers:
  - pagination
